SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS Vols_server_simplon;
CREATE SCHEMA Vols_server_simplon;
USE Vols_server_simplon;

CREATE TABLE site (
  site_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  ville VARCHAR( 45 ) NOT NULL,
 
  PRIMARY KEY  ( site_id )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO site VALUES (NULL, "NICE");
INSERT INTO site VALUES (NULL, "PARIS");
INSERT INTO site VALUES (NULL, "GRENOBLE");
INSERT INTO site VALUES (NULL, "NANTES");
INSERT INTO site VALUES (NULL, "TOULOUSE");
INSERT INTO site VALUES (NULL, "LYON");
INSERT INTO site VALUES (NULL, "BASTIA");
INSERT INTO site VALUES (NULL, "BRIVE");

CREATE TABLE pilote (
  pilote_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom_pilote VARCHAR( 45 ) NOT NULL,
  site INT UNSIGNED  NOT NULL,
 
  PRIMARY KEY  ( pilote_id ),
  CONSTRAINT `fk_pilote_site_site` FOREIGN KEY ( site ) REFERENCES site ( site_id ) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO pilote VALUES ( NULL, "SERGE", 1 );
INSERT INTO pilote VALUES ( NULL, "JEAN", 2 );
INSERT INTO pilote VALUES ( NULL, "CLAUDINE", 3 );
INSERT INTO pilote VALUES ( NULL, "ROBERT", 4 );
INSERT INTO pilote VALUES ( NULL, "MICHEL", 2 );
INSERT INTO pilote VALUES ( NULL, "LUCIENNE", 5 );
INSERT INTO pilote VALUES ( NULL, "BERTRAND", 6 );
INSERT INTO pilote VALUES ( NULL, "HERVE", 7 );
INSERT INTO pilote VALUES ( NULL, "LUC", 2 );

CREATE TABLE constructeur (
  constructeur_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom_constructeur VARCHAR( 45 ) NOT NULL,
 
  PRIMARY KEY  ( constructeur_id )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO constructeur VALUES ( NULL, "AIRBUS" );
INSERT INTO constructeur VALUES ( NULL, "BOEING" );
INSERT INTO constructeur VALUES ( NULL, "CARAVELLE" );
INSERT INTO constructeur VALUES ( NULL, "ATR" );

CREATE TABLE avion  (
  avion_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  constructeur INT UNSIGNED NOT NULL,
  modele VARCHAR( 45 ) NOT NULL,
  capacite INT UNSIGNED,
  site INT UNSIGNED NOT NULL,
  
  PRIMARY KEY  ( avion_id ),
  CONSTRAINT `fk_avion_constructeur_constructeur` FOREIGN KEY ( constructeur ) REFERENCES constructeur ( constructeur_id ) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_avion_site_site` FOREIGN KEY ( site ) REFERENCES site ( site_id ) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO avion VALUES ( NULL, 1, "A320", 300, 1 );
INSERT INTO avion VALUES ( NULL, 2, "B707", 250, 2 );
INSERT INTO avion VALUES ( NULL, 1, "A320", 300, 5 );
INSERT INTO avion VALUES ( NULL, 3, "Caravelle", 200 , 5 );
INSERT INTO avion VALUES ( NULL, 2, "B747", 400 , 2 );
INSERT INTO avion VALUES ( NULL, 1, "A320", 300, 3 );
INSERT INTO avion VALUES ( NULL, 4, "ATR42", 50, 2 );
INSERT INTO avion VALUES ( NULL, 2, "B727", 300, 6 );
INSERT INTO avion VALUES ( NULL, 2, "B727", 300, 4 );
INSERT INTO avion VALUES ( NULL, 1, "A340", 350, 7 );


CREATE TABLE vol (
  vol_id VARCHAR( 5 )   NOT NULL ,
  avion INT UNSIGNED NOT NULL,
  pilote INT UNSIGNED NOT NULL,
  ville_depart INT UNSIGNED NOT NULL,
  ville_arriver INT UNSIGNED NOT NULL,
  
  PRIMARY KEY  ( vol_id ),
  CONSTRAINT `fk_vol_avion_avion` FOREIGN KEY ( avion ) REFERENCES avion ( avion_id ) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_vol_pilote_pilote` FOREIGN KEY ( pilote ) REFERENCES pilote ( pilote_id ) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_vol_site_villeDepart` FOREIGN KEY ( ville_depart ) REFERENCES site ( site_id ) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_vol_site_villeArriver` FOREIGN KEY ( ville_arriver ) REFERENCES site ( site_id ) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO vol VALUES ( "IT100", 1, 1, 1, 2 );
INSERT INTO vol VALUES ( "IT101", 1, 2, 2, 5);
INSERT INTO vol VALUES ( "IT102", 2, 1, 2, 1 );
INSERT INTO vol VALUES ( "IT103", 6, 3, 3, 5 );
INSERT INTO vol VALUES ( "IT104", 6 , 3, 5 , 3 );
INSERT INTO vol VALUES ( "IT105", 8, 7, 6, 2 );
INSERT INTO vol VALUES ( "IT106", 10, 8, 7, 2);
INSERT INTO vol VALUES ( "IT107", 7, 9, 2, 8);
INSERT INTO vol VALUES ( "IT108", 7, 9, 8, 2);
INSERT INTO vol VALUES ( "IT109", 8, 7, 2,6 );
INSERT INTO vol VALUES ( "IT110", 3, 2, 5, 2 );
INSERT INTO vol VALUES ( "IT111", 2, 4, 1, 4);


CREATE TABLE piloter (
  date_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  vol_id VARCHAR( 5 )  NOT NULL,
  pilote_id INT UNSIGNED NOT NULL,
  date_depart DATE,
  heure_depart TIME,
  date_arriver DATE,
  heure_arriver TIME,
  
  PRIMARY KEY  ( date_id, pilote_id, vol_id ),
  CONSTRAINT `fk_piloter_pilote_piloteId` FOREIGN KEY ( pilote_id ) REFERENCES pilote ( pilote_id ) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_piloter_vol_volId` FOREIGN KEY ( vol_id ) REFERENCES vol ( vol_id ) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO piloter VALUES (NULL, 'IT100',  1, NULL,  '07:00:00', NULL, '09:00:00');
INSERT INTO piloter VALUES (NULL, 'IT101', 2, NULL,  '11:00:00', NULL, '12:00:00');
INSERT INTO piloter VALUES (NULL, 'IT102',  1, NULL,  '12:00:00', NULL, '14:00:00');
INSERT INTO piloter VALUES (NULL, 'IT103',  3,  NULL, '09:00:00', NULL, '11:00:00');
INSERT INTO piloter VALUES (NULL, 'IT104',  3, NULL,  '17:00:00', NULL,  '19:00:00');
INSERT INTO piloter VALUES (NULL, 'IT105',  7, NULL,  '06:00:00', NULL, '07:00:00');
INSERT INTO piloter VALUES (NULL, 'IT106',  8, NULL,  '10:00:00', NULL, '13:00:00');
INSERT INTO piloter VALUES (NULL, 'IT107',  9, NULL,  '07:00:00', NULL, '08:00:00');
INSERT INTO piloter VALUES (NULL, 'IT108',  9, NULL,  '19:00:00', NULL, '20:00:00');
INSERT INTO piloter VALUES (NULL, 'IT109',  7, NULL, '18:00:00', NULL, '19:00:00');
INSERT INTO piloter VALUES (NULL, 'IT110',  2, NULL,  '15:00:00',NULL,  '16:00:00');
INSERT INTO piloter VALUES (NULL, 'IT111',  4,  NULL, '17:00:00', NULL, '19:00:00');
